# Generated by Django 6.0.3 on 2026-03-27 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customuser",
            old_name="char_id",
            new_name="tg_chat_id",
        ),
    ]
