[project]
name = "termpaper5"
version = "0.1.0"
description = ""
authors = [
    {name = "timur",email = "timuryavashev@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.12,<4.0"
dependencies = [
    "django (>=6.0.3,<7.0.0)",
    "django-celery-beat (>=2.9.0,<3.0.0)",
    "pillow (>=12.1.1,<13.0.0)",
    "ipython (>=9.11.0,<10.0.0)",
    "psycopg2 (>=2.9.11,<3.0.0)",
    "djangorestframework (>=3.17.1,<4.0.0)",
    "dotenv (>=0.9.9,<0.10.0)",
    "djangorestframework-simplejwt (>=5.5.1,<6.0.0)",
    "drf-yasg (>=1.21.15,<2.0.0)",
    "redis (>=7.4.0,<8.0.0)",
    "celery (>=5.6.3,<6.0.0)",
    "eventlet (>=0.40.4,<0.41.0)",
    "requests (>=2.33.0,<3.0.0)",
    "django-cors-headers (>=4.9.0,<5.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[dependency-groups]
lint = [
    "flake8 (>=7.3.0,<8.0.0)",
    "black (>=26.3.1,<27.0.0)",
    "isort (>=8.0.1,<9.0.0)"
]

[tool.black]
# Максимальная длина строки
line-length = 119
exclude = '/(\.git|__pycache__|venv|\.venv)/'

[tool.isort]
# максимальная длина строки
line_length = 119
exclude = '/(\.git|__pycache__|venv|\.venv)/'