# Generated by Django 6.0.3 on 2026-03-27 10:25

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Wont",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("place", models.CharField(max_length=100, verbose_name="Место")),
                ("time", models.TimeField(verbose_name="Время выполнения")),
                ("action", models.CharField(max_length=100, verbose_name="Действие")),
                ("is_pleasant", models.BooleanField(default=True, verbose_name="Признак приятной привычки")),
                ("period", models.PositiveIntegerField(default=7, verbose_name="Кол-во выполнений в неделю")),
                ("reward", models.CharField(blank=True, max_length=100, null=True, verbose_name="Вознаграждение")),
                (
                    "time_to_action",
                    models.DurationField(default=datetime.timedelta(seconds=60), verbose_name="Время на выполнения"),
                ),
                ("is_published", models.BooleanField(default=True, verbose_name="Признак публичности")),
                (
                    "connection_wont",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="habits.wont",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
    ]
